# display-message "Config reloaded!"

# remove old prefix (Ctrl + `)
unbind C-\`

# set new prefix (Ctrl + Space)
set -g prefix C-Space
bind C-Space send-prefix

set -g mouse on
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

setw -g mode-keys vi

# pane Navigation
bind-key -r h select-pane -L
bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r l select-pane -R

# split window
bind v split-window -v #Vertically
bind b split-window -h #Horizontally

bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

#Swapping
bind -r > swap-pane -D       # swap current pane with the next one
bind -r < swap-pane -U       # swap current pane with the previous one

#shortcuts
bind r source-file ~/.config/tmux/tmux.conf \;
#bind r command-prompt -p "Rename Window #[fg=red]❯" "rename-window '%%'"
bind R command-prompt -p "Rename Session #[fg=red]❯" "rename-session '%%'"

# --CUSTOMIZATION------------------------------------------------------------

# Nerdfont characters
HALF_ROUND_OPEN="#(printf '\uE0B6')"
HALF_ROUND_CLOSE="#(printf '\uE0B4')"

#command-prompt
set -gF message-style "bg=default,fg=green"

#set -g status on
set -g clock-mode-style 12
set -g status-position "top"
set -g status-style bg=default
set -g status-left-style bg=default,fg=green
set -g status-left '    #[bg=default,fg=#a6e3a1]#{prefix_highlight}'

# Right area: transparent background, green text
set -g status-right-style bg=default,fg=green
# set -g status-right '#[bg=default,fg=#a6e3a1] %I:%M %p#[bg=default, fg=green]    '
# set -g status-right "#[bg=default,fg=#a6e3a1] #{b:pane_current_path}/#{pane_title} #[bg=default, fg=green]    "
set -g status-right "#[bg=default,fg=#a6e3a1] #{?#{m:*nvim*,#{pane_current_command}},/#{b:pane_current_path}/#{pane_title},#{b:pane_current_path}} #[bg=default,fg=green]    "
set-option -g status-justify centre

# Set max length of left and right section
set-option -g status-left-length 100
set-option -g status-right-length 100

# Style and set content for the inactive windows
set-option -g window-status-format "\
 \
#I\
#[fg=#939ab7]:\
#[fg=#939ab7]#W\
 \
"

# Style and set content for the active windows
set-option -g window-status-current-format "\
#[fg=#1e2030,bg=default]${HALF_ROUND_OPEN}\
#[bg=#1e2030,fg=green]#I\
#[fg=Red]:\
#[fg=green]#W\
#[fg=#1e2030,bg=default]${HALF_ROUND_CLOSE}\
"

# -- PLUGINS ----------------------------------------------------------------

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
#set -g @plugin 'fabioluciano/tmux-tokyo-night'
#set -g @plugin 'niksingh710/minimal-tmux-status'

set -g @prefix_highlight_empty_has_affixes 'on' # default is 'off'
set -g @prefix_highlight_fg 'orange'
set -g @prefix_highlight_bg 'default'
set -g @prefix_highlight_prefix_prompt '#S'
set -g @prefix_highlight_empty_prompt '#S'
set -g @prefix_highlight_output_prefix '[ '
set -g @prefix_highlight_output_suffix ' ]'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'

